name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write # required for creating release and uploading assets

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-upload:
    name: Build and Upload
    strategy:
      matrix:
        os: [ubuntu-latest, macos-15]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build msquic
      run: ./scripts/msquic.sh
    - name: Build rocksdb
      run: ./scripts/rocksdb.sh
    - name: Compress build output
      run: |
        tar czf ${{ matrix.os }}-build.tar.gz build/
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-build
        path: ${{ matrix.os }}-build.tar.gz
        retention-days: 1

  create-release:
    name: Create Release
    needs: build-and-upload
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        make_latest: true
        generate_release_notes: true
        files: |
          ubuntu-latest-build/ubuntu-latest-build.tar.gz
          macos-latest-build/macos-latest-build.tar.gz
